version: "3.3"
services:
  store:
    container_name: store
    depends_on:
      - store_db
    build:
      context: ./services/store
      dockerfile: Dockerfile
    environment:
      - MONGO_USERNAME=store
      - MONGO_PASSWORD=pass
      - MONGO_SERVER_HOST=store_db
      - MONGO_SERVER_PORT=27017
    ports:
      - "9000:9000"

  store_db:
    container_name: store_db
    image: mongo
    hostname: store-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=store
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./services/store/init-db.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"
  
  store_db_express:
    container_name: store_db_express
    image: mongo-express
    restart: always
    depends_on:
      - store_db
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=store
      - ME_CONFIG_BASICAUTH_PASSWORD=store1234
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=store-db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=store
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - store
    ports:
      - "9090:9090"
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./monitor/grafana/config.ini:/etc/grafana/grafana.ini
      - ./monitor/grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yaml
      - ./monitor/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./monitor/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
