version: '3.3'
services:
  menu:
    container_name: menu
    build:
      context: ./services/menu
      dockerfile: Dockerfile
    ports:
      - '9001:9001'
    links:
      - menu-db
    depends_on:
      - menu-db
  menu-db:
    container_name: menu-db
    image: mongo
    hostname: menu-db
    environment:
      ENV FLASK_APP: app.py
      ENV FLASK_RUN_HOST: 0.0.0.0
      MONGO_SERVER_HOST: mongo
      MONGO_SERVER_PORT: 27017
      MONGO_USERNAME: comp3122
      MONGO_PASSWORD: 12345
    volumes:
      - ./services/menu/init-db.js:/docker-entrypoint-initdb.d/mongo-init.js
    restart: on-failure
