apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
    is_default: true
    basicAuth: true
    basicAuthUser: comp3122
    secureJsonData:
      basicAuthPassword: 19085314d