global:
  scrape_interval: 30s
  external_labels:
    monitor: 'app'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'store'
    scrape_interval: 15s
    static_configs:
      - targets: ['store:9000']
  - job_name: 'menu'
    scrape_interval: 15s
    static_configs:
      - targets: ['menu:9001']
  - job_name: 'authentication'
    scrape_interval: 15s
    static_configs:
      - targets: ['authentication:9004']
  - job_name: 'apiGateway'
    scrape_interval: 15s
    static_configs:
      - targets: ['envoy:9900', 'envoy:10000']
